export const RECEIVE_CURRENT_USER = "RECEIVE_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const RECEIVE_SESSION_ERRORS = "RECEIVE_SESSION_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_REPOSITORIES = "GET_REPOSITORIES";
export const GET_REPOSITORY = "GET_REPOSITORY";
export const DELETE_REPOSITORY = "DELETE_REPOSITORY";

